[tools]
node = "latest"
java = "25"
dotnet = "9"
kotlin = { version = "2.3.20", asset_pattern = "kotlin-compiler-*.zip", bin_path = "kotlinc/bin" }
clojure = "latest"
leiningen = "latest"
babashka = "latest"
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:mvdan.cc/gofumpt" = "latest"
